# Generated by Django 3.1.3 on 2020-11-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('specie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.specie')),
            ],
        ),
        migrations.CreateModel(
            name='TreeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('trees', models.ManyToManyField(to='api.Tree')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name='Informations')),
                ('harvest_date', models.DateField()),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Gross weight')),
                ('tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tree')),
                ('tree_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.treegroup')),
            ],
        ),
    ]
